title: Jessica Lee
author: Jessica Lee
theme: minima
email: jlee2853@uwo.ca
header_pages:
  - index.md
  - resume.md
  - projects.html
  - papers.html
date: "October 2020"
kramdown:
  parse_block_html: true
# github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!
# show_excerpts: true # set to false to remove excerpts on the homepage
